name: Code Quality

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

permissions:
  contents: read
  pull-requests: read

jobs:
  code-quality:
    name: Verify Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.22.x
          cache: false

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout=5m

      - name: Test
        run: go test -coverprofile coverage.out -v ./...