name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request_target:
    types: [ opened, reopened, synchronize ]

permissions:
  contents: read

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    name: Update Release Draft
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          commitish: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
